/**
 * Scored moodboard seed tiles (optimised WebP in /public/moodboard).
 * Scores from moodboard-scores.json (google/gemini-2.5-flash, 2026-09-24, relative set-wide scoring).
 */
import type { MoodTile } from "./moodboard";

export const MOODBOARD_IMAGE_BASE = "/moodboard";

type SeedScores = {
  humanPresence: number;
  styleGlam: number;
  sparseDense: number;
  material: number;
  colorTemp: number;
  lightHardness: number;
  framing: number;
  candor: number;
  tone: number;
  tension: number;
};

type SeedRow = {
  id: string;
  file: string;
  caption: string;
  aspect: number;
  scores: SeedScores;
};

const SEED_ROWS: SeedRow[] = [
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13854",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13854.webp",
    caption: "Pensive woman with wine at a formal, minimalist dinner setting.",
    aspect: 0.75,
    scores: {
      humanPresence: 0.9,
      styleGlam: 0.8,
      sparseDense: 0.4,
      material: 0.3,
      colorTemp: 0.2,
      lightHardness: 0.25,
      framing: 0.4,
      candor: 0.1,
      tone: 0.5,
      tension: 0.2,
    },
  },
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13875",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13875.webp",
    caption: "Precariously stacked plates and cubes linked by a delicate gold chain.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.7,
      sparseDense: 0.3,
      material: 0.7,
      colorTemp: 0.3,
      lightHardness: 0.25,
      framing: 0.5,
      candor: 0.1,
      tone: 0.4,
      tension: 0.6,
    },
  },
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13885",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13885.webp",
    caption: "Golden credit card impaled by a fork, symbolizing modern consumption.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.6,
      sparseDense: 0.1,
      material: 0.9,
      colorTemp: 0.6,
      lightHardness: 0.45,
      framing: 0.3,
      candor: 0,
      tone: 0.1,
      tension: 0.5,
    },
  },
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13887",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13887.webp",
    caption: "Butter stick adorned with a sparkling necklace on a silver dish.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.7,
      sparseDense: 0.2,
      material: 0.4,
      colorTemp: 0.3,
      lightHardness: 0.25,
      framing: 0.4,
      candor: 0.05,
      tone: 0.2,
      tension: 0.1,
    },
  },
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13895",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13895.webp",
    caption: "Young woman playfully bites a gold chain, dramatic close-up.",
    aspect: 0.75,
    scores: {
      humanPresence: 1,
      styleGlam: 0.9,
      sparseDense: 0.8,
      material: 0.2,
      colorTemp: 0.3,
      lightHardness: 0.35,
      framing: 0.1,
      candor: 0.1,
      tone: 0.3,
      tension: 0.6,
    },
  },
  {
    id: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13898",
    file: "DTS_EAT_RICH_Fanette_Guilloud_Photos_ID13898.webp",
    caption: "Fish with a gold watch on an oval plate, surreal still life.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.8,
      sparseDense: 0.3,
      material: 0.5,
      colorTemp: 0.5,
      lightHardness: 0.25,
      framing: 0.5,
      candor: 0,
      tone: 0.2,
      tension: 0.4,
    },
  },
  {
    id: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15146",
    file: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15146.webp",
    caption: "Lush, dense bouquet of colorful flowers in a glass vase.",
    aspect: 0.667,
    scores: {
      humanPresence: 0,
      styleGlam: 0.4,
      sparseDense: 0.8,
      material: 0.9,
      colorTemp: 0.5,
      lightHardness: 0.25,
      framing: 0.3,
      candor: 0.2,
      tone: 0.3,
      tension: 0.05,
    },
  },
  {
    id: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15148",
    file: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15148.webp",
    caption: "Delicate pink flowers submerged in water, creating soft reflections.",
    aspect: 0.667,
    scores: {
      humanPresence: 0,
      styleGlam: 0.5,
      sparseDense: 0.8,
      material: 0.9,
      colorTemp: 0.4,
      lightHardness: 0.05,
      framing: 0.2,
      candor: 0.1,
      tone: 0.3,
      tension: 0,
    },
  },
  {
    id: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15164",
    file: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15164.webp",
    caption: "Woman bathed in milky water surrounded by an array of flowers.",
    aspect: 0.667,
    scores: {
      humanPresence: 0.95,
      styleGlam: 0.8,
      sparseDense: 0.6,
      material: 0.5,
      colorTemp: 0.6,
      lightHardness: 0.15,
      framing: 0.6,
      candor: 0.1,
      tone: 0.3,
      tension: 0.1,
    },
  },
  {
    id: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15165",
    file: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15165.webp",
    caption: "Overhead view of a bath filled with beautiful, colorful floating flowers.",
    aspect: 0.667,
    scores: {
      humanPresence: 0,
      styleGlam: 0.6,
      sparseDense: 0.9,
      material: 1,
      colorTemp: 0.5,
      lightHardness: 0.05,
      framing: 0.8,
      candor: 0.1,
      tone: 0.2,
      tension: 0,
    },
  },
  {
    id: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15193",
    file: "DTS_Flower_Bath_Riccardo_Contrino_Photos_ID15193.webp",
    caption: "Extreme close-up of lips holding a small delicate white flower.",
    aspect: 0.667,
    scores: {
      humanPresence: 0.8,
      styleGlam: 0.6,
      sparseDense: 0.9,
      material: 0.8,
      colorTemp: 0.3,
      lightHardness: 0.15,
      framing: 0,
      candor: 0.1,
      tone: 0.3,
      tension: 0.1,
    },
  },
  {
    id: "DTS_LANDING_SITE_Fanette_Guilloud_Photos_ID14966",
    file: "DTS_LANDING_SITE_Fanette_Guilloud_Photos_ID14966.webp",
    caption: "Striking portrait of a woman with avant-garde makeup holding a perfume.",
    aspect: 0.7998,
    scores: {
      humanPresence: 1,
      styleGlam: 1,
      sparseDense: 0.8,
      material: 0.5,
      colorTemp: 0.9,
      lightHardness: 0.6,
      framing: 0.2,
      candor: 0,
      tone: 0.8,
      tension: 0.7,
    },
  },
  {
    id: "DTS_LANDING_SITE_Fanette_Guilloud_Photos_ID14971",
    file: "DTS_LANDING_SITE_Fanette_Guilloud_Photos_ID14971.webp",
    caption: "Golden liquid with delicate bubbles in a glass, abstract close-up.",
    aspect: 0.7998,
    scores: {
      humanPresence: 0,
      styleGlam: 0.3,
      sparseDense: 0.7,
      material: 0.4,
      colorTemp: 0,
      lightHardness: 0.15,
      framing: 0.2,
      candor: 0.1,
      tone: 0.2,
      tension: 0,
    },
  },
  {
    id: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14031",
    file: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14031.webp",
    caption: "Woman paints nails, a gun lies nearby, under warm lamplight.",
    aspect: 0.667,
    scores: {
      humanPresence: 0.9,
      styleGlam: 0.8,
      sparseDense: 0.6,
      material: 0.5,
      colorTemp: 0.1,
      lightHardness: 0.35,
      framing: 0.5,
      candor: 0.1,
      tone: 0.6,
      tension: 0.8,
    },
  },
  {
    id: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14033",
    file: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14033.webp",
    caption: "A gun and luxury items scattered on a bed, hinting at drama.",
    aspect: 0.7148,
    scores: {
      humanPresence: 0,
      styleGlam: 0.7,
      sparseDense: 0.8,
      material: 0.8,
      colorTemp: 0.2,
      lightHardness: 0.35,
      framing: 0.6,
      candor: 0.1,
      tone: 0.7,
      tension: 0.9,
    },
  },
  {
    id: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14050",
    file: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14050.webp",
    caption: "Glamorous woman in fur coat sits outside a house at dusk.",
    aspect: 1.5015,
    scores: {
      humanPresence: 0.9,
      styleGlam: 0.95,
      sparseDense: 0.7,
      material: 0.5,
      colorTemp: 0.7,
      lightHardness: 0.7,
      framing: 0.9,
      candor: 0.05,
      tone: 0.7,
      tension: 0.6,
    },
  },
  {
    id: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14063",
    file: "DTS_MAKESHIFT_Julien_Tell_Photos_ID14063.webp",
    caption: "Woman in hair rollers applies lipstick, reflected in a mirror.",
    aspect: 0.667,
    scores: {
      humanPresence: 0.95,
      styleGlam: 0.85,
      sparseDense: 0.6,
      material: 0.5,
      colorTemp: 0.05,
      lightHardness: 0.35,
      framing: 0.4,
      candor: 0.2,
      tone: 0.6,
      tension: 0.3,
    },
  },
  {
    id: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15668",
    file: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15668.webp",
    caption: "Three interconnected circuit boards appear to float in white space.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.4,
      sparseDense: 0.2,
      material: 1,
      colorTemp: 0.8,
      lightHardness: 0.15,
      framing: 0.5,
      candor: 0,
      tone: 0.5,
      tension: 0.1,
    },
  },
  {
    id: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15669",
    file: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15669.webp",
    caption: "Circuit board adorned with a delicate pearl necklace on a notebook.",
    aspect: 0.75,
    scores: {
      humanPresence: 0,
      styleGlam: 0.5,
      sparseDense: 0.6,
      material: 0.9,
      colorTemp: 0.7,
      lightHardness: 0.35,
      framing: 0.4,
      candor: 0,
      tone: 0.2,
      tension: 0.3,
    },
  },
  {
    id: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15670",
    file: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15670.webp",
    caption: "Overhead view of various computer components laid out on a grid.",
    aspect: 0.667,
    scores: {
      humanPresence: 0,
      styleGlam: 0.3,
      sparseDense: 0.9,
      material: 1,
      colorTemp: 1,
      lightHardness: 0.45,
      framing: 0.7,
      candor: 0.3,
      tone: 0.6,
      tension: 0.5,
    },
  },
  {
    id: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15688",
    file: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15688.webp",
    caption: "Hands typing on a keyboard surrounded by electronics and small objects.",
    aspect: 0.667,
    scores: {
      humanPresence: 0.1,
      styleGlam: 0.4,
      sparseDense: 0.8,
      material: 0.95,
      colorTemp: 0.8,
      lightHardness: 0.15,
      framing: 0.6,
      candor: 0.4,
      tone: 0.4,
      tension: 0.1,
    },
  },
  {
    id: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15705",
    file: "DTS_SOFT_CIRCUITS_Julien_Tell_Photos_ID15705.webp",
    caption: "Woman in fashion attire thoughtfully examines disassembled electronic components.",
    aspect: 0.75,
    scores: {
      humanPresence: 0.9,
      styleGlam: 0.9,
      sparseDense: 0.6,
      material: 0.6,
      colorTemp: 0.7,
      lightHardness: 0.35,
      framing: 0.5,
      candor: 0.1,
      tone: 0.5,
      tension: 0.2,
    },
  }
];

function tintForScores(scores: SeedScores): string {
  const angle = 90 + scores.humanPresence * 120 + scores.sparseDense * 60;
  const a = 0.08 + scores.styleGlam * 0.1;
  const b = 0.12 + scores.material * 0.12;
  return `linear-gradient(${angle.toFixed(0)}deg, rgb(0 0 255 / ${a.toFixed(2)}), rgb(0 0 255 / ${b.toFixed(2)}))`;
}

/** Real photo tiles positioned by axis scores. */
export const MOODBOARD_SEED_TILES: MoodTile[] = SEED_ROWS.map((row) => ({
  id: row.id,
  caption: row.caption,
  prompt: row.caption,
  scores: row.scores,
  src: `${MOODBOARD_IMAGE_BASE}/${row.file}`,
  aspect: row.aspect,
  tint: tintForScores(row.scores),
}));
